name: cep_aberto_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  mobx: ^2.3.3+2
  mocktail: ^1.0.3
  responsive_builder: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/
